In [2]:
item_list = ['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
student_marks = [78, 47, 96, 55, 34]
print (item_list)
print (student_marks)

['Bread', 'Milk', 'Eggs', 'Butter', 'Cocoa']
[78, 47, 96, 55, 34]


In [3]:
student_marks = [78, 47, 96, 55, 34]
for i in range(len(student_marks)):
    student_marks[i]+=5
print(student_marks)

[83, 52, 101, 60, 39]


In [12]:
#Used to calculate total operation time
list1 = list(range(1,1000000))
list1

[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [13]:
list2 = list(range(2,1000001))
list2

[2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 1

In [15]:
list1 = list(range(1,1000000))
list2 = list(range(2,1000001))
list3 = []
list3.append(list1+list2)
list3

[[1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14,
  15,
  16,
  17,
  18,
  19,
  20,
  21,
  22,
  23,
  24,
  25,
  26,
  27,
  28,
  29,
  30,
  31,
  32,
  33,
  34,
  35,
  36,
  37,
  38,
  39,
  40,
  41,
  42,
  43,
  44,
  45,
  46,
  47,
  48,
  49,
  50,
  51,
  52,
  53,
  54,
  55,
  56,
  57,
  58,
  59,
  60,
  61,
  62,
  63,
  64,
  65,
  66,
  67,
  68,
  69,
  70,
  71,
  72,
  73,
  74,
  75,
  76,
  77,
  78,
  79,
  80,
  81,
  82,
  83,
  84,
  85,
  86,
  87,
  88,
  89,
  90,
  91,
  92,
  93,
  94,
  95,
  96,
  97,
  98,
  99,
  100,
  101,
  102,
  103,
  104,
  105,
  106,
  107,
  108,
  109,
  110,
  111,
  112,
  113,
  114,
  115,
  116,
  117,
  118,
  119,
  120,
  121,
  122,
  123,
  124,
  125,
  126,
  127,
  128,
  129,
  130,
  131,
  132,
  133,
  134,
  135,
  136,
  137,
  138,
  139,
  140,
  141,
  142,
  143,
  144,
  145,
  146,
  147,
  148,
  149,
  150,
  151,
  152,
  153,
  154,
  155,
  156,
  157,
  158,
  

In [5]:
%%time
#Used to calculate total operation time
#Importing Numpy
import numpy as np
#Creating a numpy array of 1 million numbers
a = np.arange(1,1000000)
b = np.arange(2,1000001)
c = a+b

CPU times: total: 0 ns
Wall time: 73.5 ms


In [6]:
import numpy as np
#creating a list of lists of 5 mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from car_attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr


array([[ 18,  15,  18,  16,  17],
       [130, 165, 150, 150, 140],
       [307, 350, 318, 304, 302]])

In [7]:
#creating a list of lists of  mpg, horsepower and acceleration values
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
#creating a numpy array from attributes list
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.shape

(3, 5)

In [8]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes)
car_attributes_arr.dtype



dtype('int32')

In [9]:
car_attributes = [[18, 15, 18, 16, 17],[130, 165, 150, 150, 140],[307, 350, 318, 304, 302]]
car_attributes_arr = np.array(car_attributes, dtype = 'float')
print(car_attributes_arr)
print(car_attributes_arr.dtype)

[[ 18.  15.  18.  16.  17.]
 [130. 165. 150. 150. 140.]
 [307. 350. 318. 304. 302.]]
float64


In [16]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
cars[1]

'buick skylark 320'

In [17]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140']], dtype='<U25')

In [18]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing car names
car_hp_arr[0]

array(['chevrolet chevelle malibu', 'buick skylark 320',
       'plymouth satellite', 'amc rebel sst', 'ford torino'], dtype='<U25')

In [19]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
#Accessing horsepower
car_hp_arr[1]

array(['130', '165', '150', '150', '140'], dtype='<U25')

In [20]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,1]

'buick skylark 320'

In [21]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
car_hp_arr = np.array([car_names, horsepower])
car_hp_arr[0,-1]

'ford torino'

In [22]:
cars = np.array(['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino'])
#accessing a subset of cars from the array
cars[1:4]

array(['buick skylark 320', 'plymouth satellite', 'amc rebel sst'],
      dtype='<U25')

In [23]:
car_names = ['chevrolet chevelle malibu', 'buick skylark 320', 'plymouth satellite', 'amc rebel sst', 'ford torino']
horsepower = [130, 165, 150, 150, 140]
acceleration = [18, 15, 18, 16, 17]
car_hp_acc_arr = np.array([car_names, horsepower, acceleration])
car_hp_acc_arr

array([['chevrolet chevelle malibu', 'buick skylark 320',
        'plymouth satellite', 'amc rebel sst', 'ford torino'],
       ['130', '165', '150', '150', '140'],
       ['18', '15', '18', '16', '17']], dtype='<U25')

In [30]:
import numpy as np
hr_arr=np.array([130,165,150,150,140])
y=np.where(hr_arr>=150)
print(y)
print(hr_arr[y])

(array([1, 2, 3], dtype=int64),)
[165 150 150]


In [33]:
hr_arr=np.array([130,165,150,150,140])
x=hr_arr>135
print(x)
new_hr_arr=hr_arr[x]
print(new_hr_arr)
print(hr_arr)

[False  True  True  True  True]
[165 150 150 140]
[130 165 150 150 140]


In [34]:
horsepower_arr=np.array([130,165,150,150,140])
sort_arr=np.sort(horsepower_arr)
print(horsepower_arr)
print(sort_arr)

[130 165 150 150 140]
[130 140 150 150 165]


In [44]:
marks_arr=([67,45],[90,92],[66,72],[32,40])
marks_arr=np.array(marks_arr)
print(marks_arr)

[[67 45]
 [90 92]
 [66 72]
 [32 40]]


In [49]:
import numpy as np
marks_arr=([67,45],[90,92],[66,72],[32,40])
marks_arr=np.array(marks_arr)
marks_arr+=(5,10)
print(marks_arr)

[[ 72  55]
 [ 95 102]
 [ 71  82]
 [ 37  50]]


In [50]:
marks_arr=([67,45],[90,92],[66,72],[32,40])
marks_arr=np.array(marks_arr)
marks_arr-=(5,10)
print(marks_arr)

[[62 35]
 [85 82]
 [61 62]
 [27 30]]


In [9]:
arr = np.linspace(0,10)
print(arr)
print('Length of arr: ',len(arr))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
Length of arr:  50


In [11]:
x = np.random.randint(100, size=(3, 5))
print(x)
print(type(x))

[[59 63 71 48 26]
 [ 3  6 63 86 12]
 [40  4 47 51 11]]
<class 'numpy.ndarray'>


In [12]:
x = np.random.choice([9, 3, 7, 5], size=(3, 5))   # sampling to create an nd-array 
print(x)
print(type(x))

[[5 5 9 9 7]
 [3 5 5 9 3]
 [3 9 7 3 5]]
<class 'numpy.ndarray'>


In [9]:
#1.Represent the above data in a 10x2 array. In each row, the first element should contain day number and second element should contain steps walked.
day_number=np.arange(1,11)
steps_walked=[6012,7079,6886,7230,4598,5564,6971,7763,8032,9569]
arr=np.array([day_number,steps_walked])
arr=arr.T
arr

array([[   1, 6012],
       [   2, 7079],
       [   3, 6886],
       [   4, 7230],
       [   5, 4598],
       [   6, 5564],
       [   7, 6971],
       [   8, 7763],
       [   9, 8032],
       [  10, 9569]])

In [10]:
#2.Lee notices that the tracker’s battery dies every day at 7 pm. Lee discovers that on an average,he walks 2000 steps every day after 7 pm. Perform an appropriate operation on your array to add 2000 steps to all the observations.
new_arr=arr[:,1]+2000
arr[:,1]=new_arr
arr

array([[    1,  8012],
       [    2,  9079],
       [    3,  8886],
       [    4,  9230],
       [    5,  6598],
       [    6,  7564],
       [    7,  8971],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [11]:
#3.Write a program that returns the steps walked if the steps walked are more than 9000.
matched=arr[:,1]>9000
matched
new_arr=arr[matched]
new_arr

array([[    2,  9079],
       [    4,  9230],
       [    8,  9763],
       [    9, 10032],
       [   10, 11569]])

In [12]:
#4.Print an array containing steps walked in sorted order.
sortedArr=arr[arr[:,1].argsort()]
print('Sorted 2D Numpy Array')
print(sortedArr)

Sorted 2D Numpy Array
[[    5  6598]
 [    6  7564]
 [    1  8012]
 [    3  8886]
 [    7  8971]
 [    2  9079]
 [    4  9230]
 [    8  9763]
 [    9 10032]
 [   10 11569]]


In [14]:
#np.sum()
arr=np.array([[1,2],[3,4]])
print(np.sum(arr))
print(np.sum(arr,axis=0))
print(np.sum(arr,axis=1))

10
[4 6]
[3 7]


In [15]:
#np.mean()
arr=np.array([[1,2],[3,4]])
print(np.mean(arr))
print(np.mean(arr,axis=0))
print(np.mean(arr,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [16]:
#np.max()
arr=np.array([[1,2],[3,4]])
print(np.max(arr))
print(np.max(arr,axis=0))
print(np.max(arr,axis=1))

4
[3 4]
[2 4]


In [17]:
#np.median
arr=np.array([[1,2],[3,4]])
print(np.median(arr))
print(np.median(arr,axis=0))
print(np.median(arr,axis=1))

2.5
[2. 3.]
[1.5 3.5]


In [20]:
#np.prod()
arr=np.array([[1,2],[3,4]])
print(np.prod(arr))
print(np.prod(arr,axis=0))
print(np.prod(arr,axis=1))

24
[3 8]
[ 2 12]


In [21]:
#np.std()
arr=np.array([[1,2],[3,4]])
print(np.std(arr))
print(np.std(arr,axis=0))
print(np.std(arr,axis=1))

1.118033988749895
[1. 1.]
[0.5 0.5]


In [22]:
#np.var()
arr=np.array([[1,2],[3,4]])
print(np.var(arr))
print(np.var(arr,axis=0))
print(np.var(arr,axis=1))

1.25
[1. 1.]
[0.25 0.25]


In [26]:
#VECTORIZED OPERATIONS
#Element-wise addition:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1+arr2
print(result)

[5 7 9]


In [28]:
#Element-wise substraction
arr1=np.array([4,5,6])
arr2=np.array([1,2,3])
result=arr1-arr2
print(result)

[3 3 3]


In [29]:
#Element-wise multiplication
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
result=arr1*arr2
print(result)

[ 4 10 18]


In [31]:
#Element-wise Division
arr1=np.array([4,6,8])
arr2=np.array([2,3,4])
result=arr1/arr2
print(result)

[2. 2. 2.]


In [32]:
#Elements-wise exponentiation
arr=np.array([2,3,4])
result=arr**2
print(result)

[ 4  9 16]


In [33]:
#Element-wise square root
arr=np.array([4,9,16])
result=np.sqrt(arr)
print(result)

[2. 3. 4.]


In [35]:
#Element-wise comparison
arr1=np.array([1,2,3])
arr2=np.array([2,2,3])
result=arr1==arr2
print(result)

[False  True  True]


In [5]:
#STATISTICAL FUNCTIONS
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
result_mean=np.mean(arr)
result_std=np.std(arr,axis=1)
result_sum=np.sum(arr,axis=0)
print(result_mean)
print(result_std)
print(result_sum)

3.5
[0.81649658 0.81649658]
[5 7 9]


In [9]:
#Element-wise rounding
arr=np.array([2.3,4.7,6.1])
result=np.round(arr)
print(result)

[2. 5. 6.]


In [11]:
#Element-wise exponentiation with a scalar
arr=np.array([2,3,4])
result=np.power(arr,2)
print(result)

[ 4  9 16]


In [12]:
#Element-wise comparison and assignment
arr=np.array([1,5,10])
result=np.where(arr<5,arr,0)
print(result)

[1 0 0]


In [13]:
#Element-wise cumulative sum
arr=np.array([1,2,3,4,5])
result=np.cumsum(arr)
print(result)

[ 1  3  6 10 15]


In [14]:
#Element-wise sorting
arr=np.array([3,1,4,2,5])
result=np.sort(arr)
print(result)

[1 2 3 4 5]


In [21]:
#Vectorized operations Exercise
S_X=np.array([[2,5,6,5],[4,8,6,5]])
S_Y=np.array([[6,7,5,9],[7,5,6,4]])
quaterly_difference=S_Y-S_X
print(quaterly_difference)

[[ 4  2 -1  4]
 [ 3 -3  0 -1]]


In [23]:
less_than_2=S_X<2
print(less_than_2)

[[False False False False]
 [False False False False]]


In [27]:
X_cumsum=np.cumsum(S_X,axis=1) 
print(X_cumsum)
print(X_cumsum>=8)

[[ 2  7 13 18]
 [ 4 12 18 23]]
[[False False  True  True]
 [False  True  True  True]]


In [30]:
Y_cumsum=np.cumsum(S_Y,axis=1)
print(Y_cumsum)
print(Y_cumsum>=8)

[[ 6 13 18 27]
 [ 7 12 18 22]]
[[False  True  True  True]
 [False  True  True  True]]


In [34]:
yearly_mean_X=np.mean(S_X,axis=1)
print(yearly_mean_X)

[4.5  5.75]


In [35]:
quaterly_mean_Y=np.mean(S_X,axis=1)
print(quaterly_mean_Y)

[4.5  5.75]


In [37]:
#Use map, filter, reduce and lambda functions with numpy
#squaring each number using map()
numbers=[1,2,3,4,5]
squared_numbers=map(lambda x:x**2,numbers)
print(list(squared_numbers))

[1, 4, 9, 16, 25]


In [38]:
#"Filtering even numbers using filter()
numbers=[1,2,3,4,5]
even_numbers=filter(lambda x:x%2==0,numbers)
print(list(even_numbers))

[2, 4]


In [40]:
#summing all the numbers using reduce()
from functools import reduce
numbers=[1,2,3,4,5]
sum_of_numbers=reduce(lambda x, y:x+y,numbers)
print(sum_of_numbers)

15


In [2]:
#squaring a number using a lambda function
square=lambda x:x**2
print(square(5))

25
